FROM node:18-alpine
EXPOSE 3001
WORKDIR /app 
ENV NODE_ENV=development 
COPY package.json package-lock.json ./ 
COPY apps/server/package.json ./apps/server/package.json
RUN ["npm", "install"]
COPY . . 
CMD ["npm", "run", "dev", "-w", "@music-platform/server"]

