services:
  server:
    build: packages/server/
    ports:
      - 3001:3001
    env_file: packages/server/.env
    depends_on:
      - db
    healthcheck:
      test: wget --spider http://localhost:3001/api/test || exit 1
      interval: 15s
      retries: 3
      timeout: 5s

  db:
    image: mongodb/mongodb-community-server
    volumes:
      - db_vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
volumes:
  db_vol:
