services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - server
    healthcheck:
      test: wget --spider http://localhost:3000 || exit 1
      interval: 15s
      retries: 3
      timeout: 5s

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 3001:3001
    env_file: apps/server/.env
    depends_on:
      - db
    healthcheck:
      test: wget --spider http://localhost:3001/api/test || exit 1
      interval: 15s
      retries: 3
      timeout: 5s

  db:
    image: mongodb/mongodb-community-server
    volumes:
      - db_vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
volumes:
  db_vol:
